version: 0.2
#test
phases:
  install:
    commands:
      - npm install
      - echo "test699080-12345678910"
      - sleep 5s
  build:
    commands:
      - npm test
artifacts:
  files:
    - '**/*'
